site_name: Pesto Docs
site_description: A tiny lua framework.
site_author: Vinny Horgan
copyright: Copyright © 2023 Vinny Horgan
nav:
  - Introduction: "index.md"
  - Features: "features.md"
  - Getting Started: "getting_started.md"
  - Modules:
    - pesto: "modules/pesto.md"
    - pesto.audio: "modules/audio.md"
    - pesto.system: "modules/system.md"
theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: material/leaf
  palette:
    scheme: slate
    primary: green
    accent: green
  features:
    - navigation.sections
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vinnyhorgan/pesto
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
