site_name: Pesto Docs
site_description: A tiny lua framework.
site_author: Vinny Horgan
copyright: Copyright © 2023 Vinny Horgan
nav:
  - Introduction: "index.md"
  - Features: "features.md"
  - Getting Started: "getting_started.md"
  - Building: "building.md"
  - Modules:
    - pesto: "modules/pesto.md"
    - pesto.animation: "modules/animation.md"
    - pesto.astar: "modules/astar.md"
    - pesto.audio: "modules/audio.md"
    - pesto.collision: "modules/collision.md"
    - pesto.ecs: "modules/ecs.md"
    - pesto.filesystem: "modules/filesystem.md"
    - pesto.gamepad: "modules/gamepad.md"
    - pesto.graphics: "modules/graphics.md"
    - pesto.imgui: "modules/imgui.md"
    - pesto.inspect: "modules/inspect.md"
    - pesto.json: "modules/json.md"
    - pesto.keyboard: "modules/keyboard.md"
    - pesto.ldtk: "modules/ldtk.md"
    - pesto.log: "modules/log.md"
    - pesto.math: "modules/math.md"
    - pesto.mouse: "modules/mouse.md"
    - pesto.reload: "modules/reload.md"
    - pesto.rres: "modules/rres.md"
    - pesto.signal: "modules/signal.md"
    - pesto.state: "modules/state.md"
    - pesto.system: "modules/system.md"
    - pesto.tween: "modules/tween.md"
    - pesto.util: "modules/util.md"
    - pesto.window: "modules/window.md"
  - Objects:
    - pesto.Object: "objects/object.md"
    - pesto.Vector: "objects/vector.md"
  - Extra Modules:
    - enet: "extra_modules/enet.md"
    - http: "extra_modules/http.md"
    - utf8: "extra_modules/utf8.md"
theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: material/leaf
  palette:
    scheme: slate
    primary: green
    accent: green
  features:
    - navigation.sections
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vinnyhorgan/pesto
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
