site_name: Pesto Docs
site_author: Vinny Horgan
copyright: Copyright © 2023 Vinny Horgan
theme:
  name: material
  favicon: assets/favicon.png
  palette:
    scheme: slate
    primary: green
    accent: green
  features:
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: "index.md"
  - Modules:
    - pesto: "modules/pesto.md"
    - pesto.audio: "modules/audio.md"
    - pesto.system: "modules/system.md"
